kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: Helloworld
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: Helloworld_auto_scale
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60