kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: helloworld-auto-scale
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: helloworld
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60