---

- name: Deply hellowworld by helm
  shell: helm install helloworld kubernetes-helm-hello-world/helloworld-chart

#- name: Deply hellowworld by helm
#  helm:
#    chart:
#      source:
#        type: git
#        location: https://github.com/pablorsk/kubernetes-helm-hello-world.git
#        path: helloworld-chart
#    state: present
#    name: hellowworld
#    namespace: default


- name: Create autoscale for helloworld
  shell: kubectl apply -f roles/helloworld/files/auto_scale.yml

- name: Create schedule autoscale for helloworld
  shell: kubectl apply -f roles/helloworld/files/schedule_scale.yml

#
#- name: Create autoscale for helloworld
#  k8s:
#    state: present
#    src: roles/helloworld/files/auto_scale.yml
#
#- name: Create schedule autoscale for helloworld
#  k8s:
#    state: present
#    src: roles/helloworld/files/schedule_scale.yml
#
